spring:
  shardingsphere:
    datasource:
      ds0:
        driver-class-name: com.mysql.jdbc.Driver
        password: flyonsky
        type: org.apache.commons.dbcp2.BasicDataSource
        url: jdbc:mysql://localhost:3306/flyonsky0
        username: root
      ds1:
        driver-class-name: com.mysql.jdbc.Driver
        password: flyonsky
        type: org.apache.commons.dbcp2.BasicDataSource
        url: jdbc:mysql://localhost:3306/flyonsky1
        username: root
      names: ds0,ds1
    sharding:
      default-database-strategy:
        inline:
          algorithm-expression: ds$->{user_id % 2}
          sharding-column: user_id
      tables:
        t_order:
          actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
          table-strategy:
            inline:
              algorithm-expression: t_order$->{order_id % 2}
              sharding-column: order_id
        t_order_item:
          actual-data-nodes: ds$->{0..1}.t_order_item$->{0..1}
          table-strategy:
            inline:
              algorithm-expression: t_order_item$->{order_id % 2}
              sharding-column: order_id