spring:
  shardingsphere:
    datasource:
      ds0:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/flyonsky0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: flyonsky
        auto-commit: true
        connection-test-query: SELECT 1
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 1800000
        maximum-pool-size: 15
        minimum-idle: 5
        pool-name: HikariCP-ds0
      ds1:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/flyonsky1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: flyonsky
        auto-commit: true
        connection-test-query: SELECT 1
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 1800000
        maximum-pool-size: 15
        minimum-idle: 5
        pool-name: HikariCP-ds1
      names: ds0,ds1
    sharding:
      default-database-strategy:
        inline:
          algorithm-expression: ds$->{user_id % 2}
          sharding-column: user_id
      tables:
        t_order:
          actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
          table-strategy:
            inline:
              algorithm-expression: t_order$->{order_id % 2}
              sharding-column: order_id
        t_order_item:
          actual-data-nodes: ds$->{0..1}.t_order_item$->{0..1}
          table-strategy:
            inline:
              algorithm-expression: t_order_item$->{order_id % 2}
              sharding-column: order_id
        t_user:
          actual-data-nodes=ds$->{0}.t_user:
      binding-tables: t_order,t_order_item
      broadcast-tables: t_user