spring:
  application:
    name: mybatis
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/flyonsky?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: HikariCP
      username: root
      password: flyonsky

mybatis:
  mapper-locations: com/flyonsky/mapper/*.xml

logging:
  level:
    org:
      mybatis: ERROR
      springframework: DEBUG
  file: /app/logs/${spring.application.name}.log

server:
  servlet:
    context-path: /
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - threaddump
          - metrics
          - logfile
          - env
  endpoint:
    health:
      show-details: always